---
- hosts: myWebservers
  become: yes
  tasks:
   - name: i want to install git,tree and wget
     apt:
      name: "{{item}}"
      state: present
     loops:
      - tree:
      - wget:
      - git:  