---
- hosts: [myWebservers]
  become: yes
  tasks:
   - name: i want to install webserver on ubunt
     apt:
      name: apache2
      state: present
     when: ansible_os_family== "Debian"
   - name: i want o start webserver on ubuntu
     service:
      name: apache2
      state: started
     when:  ansible_os_family== "Debian"

   - name: i want to install wenser on linux
     yum:
      name: httpd
      state: present  
     when:  ansible_os_family== "RedHat"

   - name: i want to install webserver on redhat liux
     service:
      name: httpd
      state: started
     when:  ansible_os_family== "RedHat"  